<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Index suffix
    |--------------------------------------------------------------------------
    |
    | The bm25 index name is being automatically generated by concatenating
    | the table name, e.g. `products`, with the suffix below to then get
    | `products_idx`.
    |
    */

    'index_suffix' => env('PG_SEARCH_INDEX_SUFFIX', '_idx'),

    /*
    |--------------------------------------------------------------------------
    | Highlighting tag
    |--------------------------------------------------------------------------
    |
    | Set a global highlighting tag when using the `Snippet` expression. Must
    | include the closing tag!
    |
    */
    'highlighting_tag' => env('PG_SEARCH_HIGHLIGHTING_TAG', '<b></b>'),
];
