<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Index suffix
    |--------------------------------------------------------------------------
    |
    | The bm25 index name is being automatically generated by concatenating
    | the table name, e.g. `products`, with the suffix below to then get
    | `products_idx`.
    |
    */

    'index_suffix' => '_idx',
];
